### ISSUE TITLE
bootstrap datepicker 1.4 released, breaks install

### ISSUE THREAD

**Issue by ssured** [soulim/ember-cli-bootstrap-datepicker#13]
It seems a couple of minutes ago datepicker 1.4 was released.

The install process `ember install:addon ember-cli-bootstrap-datepicker` is now broken, which bit me.

It seems 1.4.0 is automatically installed by bower, the blocking issue is they moved the assets into a `dist` folder, thus ember-cli cannot find the files.

**Comment by soulim** [comment]
Thank you a lot @ssured! Will update the add-on as soon as possible.

**Comment by ssured** [comment]
:+1: !

**Comment by soulim** [comment]
Fixed in #16.
