### ISSUE TITLE
make loading of bootstrap.css optional

### ISSUE THREAD

**Issue by ssured** [soulim/ember-cli-bootstrap-datepicker#14]
right now bootstrap.css is loaded; I think this should be optional, as most projects will load bootstrap in another plugin (so you can use the LESS of SASS version of Bootstrap)

**Comment by btecu** [comment]
I don't think it loads `bootstrap.css`. You should look at `index.js` and not `broccoli.js`.

To test, in a new project, import this addon and build. Then look at the content of `vendor.css` and you'll see it doesn't contain `bootstrap.css`.

**Comment by ssured** [comment]
Ok, maybe it should be documented that bootstrap should be loaded separately. Sorry I was confused by the different addon files. Thanks
