### ISSUE TITLE
Parsed date is one day behind

### ISSUE THREAD

**Issue by btecu** [soulim/ember-cli-bootstrap-datepicker#18]
Likely related to https://github.com/soulim/ember-cli-bootstrap-datepicker/issues/15.

If I pass a date, say *2014-10-17T00:00:00*, `ember-cli-bootstrap-datepicker` will show the date before that, *2014-10-16*.

The easiest way to reproduce it is to click on the clear button and noticed that instead of clearing, it sets the date to *12/31/1969*.

**Comment by btecu** [comment]
The ``today`` button seems to be broken on the demo page too.

**Comment by palimpsests** [comment]
I'm also seeing this behavior (parsed date is one day behind).

**Comment by soulim** [comment]
Oh! That's a nasty problem :disappointed: Will double check everything.

**Comment by palimpsests** [comment]
@soulim thanks! any update?

**Comment by soulim** [comment]
There's a problem with date convertion :disappointed: Internally the add-on converts date string into Javascript Date object like `new Date("2014-10-17T00:00:00")`, but the result is local date and time and then it causes this problem.

At the beginning I thought it's a good idea to use date strings, but seems like I was wrong. So I'm going to remove conversion completely and use native Javascript Date objects everywhere. Will report about results ASAP.

**Comment by soulim** [comment]
Okay :smile: ISO date strings just got replaced with native Javascript dates. Please use master branch to play with this update because a new version of the add-on isn't released yet.

Basically instead of `2014-10-17T00:00:00` you should use `new Date(2014, 9, 17)`, and everything should work :smile: Please note that months are counted from `0` in Javascript.

I've already tested native dates locally using different time zones, and everything seems fine. Ping me if you still have problems.

**Comment by palimpsests** [comment]
@soulim nice, this is working for me! Thanks :-)

**Comment by soulim** [comment]
Just released [`v0.4.0`][1] with all new shiny updates. Please upgrade and enjoy your day :smile: 

@btecu could please let me know if the problem still exists for you. If it got fixed, feel free to close this issue.

[1]: https://github.com/soulim/ember-cli-bootstrap-datepicker/releases/tag/v0.4.0

**Comment by btecu** [comment]
I had to switch to a different library because of the issues, so I no longer can test this. Perhaps @palimpsests can report back and we'll close this issue.

**Comment by soulim** [comment]
Okay :+1: Thank you for response @btecu!
