### ISSUE TITLE
Don't load css

### ISSUE THREAD

**Issue by dinhhuydh** [soulim/ember-cli-bootstrap-datepicker#20]
Hi,

I'm using ember-cli to install the addon by running `ember install:addon ember-cli-bootstrap-datepicker`. The datepicker works fine but the css doesn't affect on the calendar. I can't find the css file like `old` `datepicker-dropdown`.
Do i need to install any addon to have the css?

**Comment by soulim** [comment]
Hey @dinhhuydh,

you don't need to install any additional add-ons, `bootstrap-datepicker` CSS-file must be injected into assets of your app automatically.

[The demo website][1] uses current version of `ember-cli-bootstrap-datepicker` add-on. You could find source code in [`tests/dummy`][2] directory.

Just like experiment you could run the demo website locally. In this case you just need to clone the repo and run `ember serve`:

```
git clone git@github.com:soulim/ember-cli-bootstrap-datepicker.git
cd ember-cli-bootstrap-datepicker
ember serve
```

The demo site should be available o default port.

Oh! Of course Boostrap CSS files must be loaded as well, but I guess you know this.

Ping me if you would still need some help.

[1]: http://sul.im/ember-cli-bootstrap-datepicker/
[2]: https://github.com/soulim/ember-cli-bootstrap-datepicker/tree/master/tests/dummy

**Comment by dinhhuydh** [comment]
Hi @soulim. Thanks for you reply.

I use the ember-cli-rails to include ember-cli into my existing Rails project. To make it works, i had to declare bootstrap css in application css file for ember.

It's good now.

**Comment by soulim** [comment]
That's great news! I wish you a wonderful day :smile:
