### ISSUE TITLE
publish to npm

### ISSUE THREAD

**Issue by ksnyde** [soulim/ember-cli-bootstrap-datepicker#24]
I noticed that you've upgraded to 0.2.2 and removed prototype extensions but it appears you haven't yet published this to NPM so I'm still getting the older version. Can you update this?

**Comment by soulim** [comment]
Sure, I can publish a new version to NPM. Actually I wanted somebody to play with these changes in master first, and then release a new version.

**Comment by soulim** [comment]
Done :smile: You could install [`v0.4.0][1] from NPM.

[1]: https://github.com/soulim/ember-cli-bootstrap-datepicker/releases/tag/v0.4.0

**Comment by ksnyde** [comment]
Great :+1:
