### ISSUE TITLE
Auto orientation is broken?

### ISSUE THREAD

**Issue by BenjaminHorn** [soulim/ember-cli-bootstrap-datepicker#25]
I made a very basic application template:
```
<p>
  Lorem ipsum dolor sit amet, consectetur adipiscing elit.
</p>

{{bootstrap-datepicker}}

{{outlet}}
```

As you can see the datepicker is completely miss positioned.
![screenshot from 2015-04-08 13 06 24](https://cloud.githubusercontent.com/assets/5570232/7044165/abbb1114-ddf0-11e4-8f5c-e4c3f1cef6dd.png)

Interestingly if I have only ```{{bootstrap-datepicker}}``` in my template, it works fine:

![screenshot from 2015-04-08 13 15 44](https://cloud.githubusercontent.com/assets/5570232/7044224/64dc0d74-ddf1-11e4-8818-ebd76f894aa9.png)

**Comment by soulim** [comment]
I guess it's a known issue https://github.com/eternicode/bootstrap-datepicker/issues/1317, and the fix is waiting for the pull request review https://github.com/eternicode/bootstrap-datepicker/pull/1329.

**Comment by BenjaminHorn** [comment]
thanks @soulim!  good to know. Let's wait for that merge.

**Comment by soulim** [comment]
Seems like this problem does not belong to the component, so I'm closing this issue. Hope it'll be fixed soon in `bootstrap-datepicker`.
