### ISSUE TITLE
Setting the `container` option

### ISSUE THREAD

**Issue by timohofmeijer** [soulim/ember-cli-bootstrap-datepicker#27]
I'd like to use `bootstrap-datepicker`’s `container` option in order to inject the picker somewhere other than the `<body>` element. 

Doe anyone know a way to accomplish this?

https://bootstrap-datepicker.readthedocs.org/en/latest/options.html#container

**Comment by soulim** [comment]
The `container` option isn't supported by the add-on yet, but it's very easy to implement.

Also I've noticed a couple of new options of `bootstrap-datepicker` that should be supported as well. Will try to implement everything ASAP. Please stay tuned :wink:

**Comment by soulim** [comment]
Just merged pull request from @minimalweb which adds `widgetContainer` option. Please use this option to set `container` parameter on `bootstrap-datepicker` widget.

This feature isn't documented yet, but update for README and demo page is coming soon.

**Comment by timohofmeijer** [comment]
Awesome!
