### ISSUE TITLE
bind to a Date object

### ISSUE THREAD

**Issue by samselikoff** [soulim/ember-cli-bootstrap-datepicker#3]
`value` should really be a bound Date object instead of a string. Would you accept a PR for this?

**Comment by jelhan** [comment]
Do you like to provide backward compatibility or is it okay to just replace date ISO strings by date objects? In long term code would be better to maintain if we don't have to support to different types of bound objects. So I would prefer switching to date objects just now and brake backward compatibility as addon is in early development stage.

**Comment by soulim** [comment]
@jelhan date objects instead of ISO date strings are planned in v1.0.0. I'm using [SemVer][1] for versioning, date objects are breaking change that's why this feature going to be introduced in v1.

Totally support the idea of supporting just one type.

[1]: http://semver.org

**Comment by jelhan** [comment]
ember-cli-bootstrap-datepicker is in 0.x versions. Therefore backward compatibility hasn't be provided following SemVer:
```
4. Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.
```
I think a fundamental change like this one should be done as early as possible in initial development.

**Comment by soulim** [comment]
Good point @jelhan! I think you are right, and this change must be introduced as soon as possible.

**Comment by ninjatronic** [comment]
@jelhan @soulim glad I saw this just now - I came here to ask for both javascript Data and also moment support. How do you feel about revising your "just one type" policy?

**Comment by jelhan** [comment]
@ninjatronic What is the issue with moment support when switching to date object. Moment is supporting date objects: http://momentjs.com/docs/#/parsing/date/

**Comment by soulim** [comment]
@ninjatronic I would prefer to have support just for native Javascript Date object. In this case the add-on doesn't have additional dependency, but you can always convert Date object into a moment or any other thing. @jelhan is right, you can easily create a moment object using native Date.

I like to keep things simple and as native as possible. Basically that was the reason why I decided not to use moment when I started working on the add-on.

**Comment by samselikoff** [comment]
Sorry I haven't had time to work on this yet. I agree, should definitely be native JS Date object. Super easy to have an Ember CP that turns it into a Moment object.

**Comment by ninjatronic** [comment]
@soulim thanks

**Comment by broerse** [comment]
@samselikoff I use momentjs (moment.locale('nl');) to show dutch dates like `moment(value).format("dddd D MMMM YYYY");` `woensdag 18 februari 2015` but how do I show the date object as the shown value for this datepicker? Do you maybe have some example code?

**Comment by soulim** [comment]
@broerse datepicker supports many languages (including [Dutch][1]).

You could find an example in README https://github.com/soulim/ember-cli-bootstrap-datepicker#language. It's just two lines of code :smile: 

`format` option could help you with exact date format you need https://github.com/soulim/ember-cli-bootstrap-datepicker#format.

Ping me if you still have some questions.

[1]: https://github.com/eternicode/bootstrap-datepicker/blob/master/dist/locales/bootstrap-datepicker.nl.min.js

**Comment by soulim** [comment]
@broerse it might be something like this for you:

```js
// Brocfile.js
app.import('bower_components/bootstrap-datepicker/js/locales/bootstrap-datepicker.nl.js');
```

```handlebars
{{! somewhere in template }}
{{bootstrap-datepicker value=someVariableWithDate language="nl" format="DD d MM yyyy"}}
```

**Comment by broerse** [comment]
Thanks. This it works. It now spells 'Februari' but in dutch you say 'februari' and `woensdag` see momentjs locale. Do you like a PR for this?

**Comment by soulim** [comment]
Oh! You are right @broerse. All localizations come from bootstrap-datepicker. The add-on uses the last version of bootstrap-datepicker (1.3.1), but it has incorrect Dutch localization (https://github.com/eternicode/bootstrap-datepicker/blob/51ffa7ec95a9d4b239f48a76e07e96c982cb5c36/js/locales/bootstrap-datepicker.nl.js). 

This problem has been fixed recently https://github.com/eternicode/bootstrap-datepicker/commit/43e66fdd97534a69d7052e3ffe8ed3d51dc3d574. Could you try to use bootstrap-datepicker from master branch instead of 1.3.1 version? That should help.

**Comment by broerse** [comment]
Thanks! I just tried but bootstrap-datepicker master breaks on some .css file. I will wait for a new stable version. I also just tried @joachimhs native date patch and it works fine.

**Comment by soulim** [comment]
Awesome! :+1: Native Dates will be implemented soon.

**Comment by btecu** [comment]
I tried binding the `bootstrap-datepicker` to my ED field that contains a date and I get an invalid date.
I get `Mon Dec 22 2014 19:00:00 GMT-0500 (Eastern Standard Time)` and it should be `2014-12-23T00:00:00.000Z`, which causes my record to be invalid and non-retrievable.

Is the lack of native dates the cause?

**Comment by broerse** [comment]
@btecu https://github.com/soulim/ember-cli-bootstrap-datepicker/pull/10 works for me.

**Comment by soulim** [comment]
Finally I've replaced ISO date strings with Javascript native date objects https://github.com/soulim/ember-cli-bootstrap-datepicker/commit/bd8e639ab8a704fde72d45da29cb6e41cb4faa40. Feel free ping me if you have questions :smiley:
