### ISSUE TITLE
How to test with ember-qunit ?

### ISSUE THREAD

**Issue by Maze-fr** [soulim/ember-cli-bootstrap-datepicker#32]
Hello,

Everything is in the title...
I don't manage to "fillin" my input for the date correctly, so it fails on ember-validations in qunit.
As my date is mandatory, and has other constraints (custom validation), I can't test anything.

How can i "fillin" my date picker so I can make my tests ?

Thanks for helping me.

**Comment by soulim** [comment]
Hey @Maze-fr! Could you show me code your test? There's no need to provide all your code. Just the part where you are trying to "fill in" the field. That would help me to reproduce your problem locally.

**Comment by Maze-fr** [comment]
I don't have the code here and now, so I make you an example.

First, in my page, I make a date picker with an ID, let's say "myDate".
I can only pick a date, not write one into the input manually.

Then, in UT, I have something like that :
```javascript
fillin(find('#myDate'), '01/01/2100');
```
For my other inputs, I do that way and it works.
I checked the DOM and my input has the ID "myDate", so it should work.

One last thing : I have an ember-validation at "required" for my date on the model.
So in my UT, I do a click on my submit button, and then I check the content of my errors in the page : I have the "value required" error for the date picker.
I guess I should trigger something, but I don't know what.

**Comment by Maze-fr** [comment]
Some more precise coding...
In the page :
```javascript
{{bootstrap-datepicker value=model.myDate id=myDate name=myDate
        format="dd/mm/yyyy" autoclose=true language="fr" weekStart=1 orientation="top"}}
```
In the model :
```javascript
MyModel.reopen({
  validations : {
    myDate: {
      presence: true
    }
  }
});
```
In the test :
```javascript
fillIn('#myDate', '01/01/2100');
```
Then I force click the submit button and I check the errors in the page : the error says the date is missing.
No problem with any other input DOM object in my form.

**Comment by soulim** [comment]
Thank you! I'll take a look how to help you with that issue.

**Comment by Maze-fr** [comment]
I did a some digging in sources, and I found that file :
```
bower_components\bootstrap-datepicker\docs\methods.rst
```
It took me some tries in console to find out that
```javascript
$('.datepicker')
```
is the reference to my input and not to the calendar (which has class ".datepicker", and my input doesn't)...

So, if i do that, it works :
```javascript
find('#myDate').datepicker('setDate', new Date(2100, 1, 1));
```
It fills the input and the validation passes through.

**Comment by gzurbach** [comment]
Thanks for the tip that worked really well. It'd be awesome to have this tip in the `README` in a "how to test" section.

**Comment by rustygeldmacher** [comment]
Hi @Maze-fr and @soulim -- have you or anyone else found a way to test the datepicker by simulating clicks? If I had a datepicker caled '#my-date', then doing `click('#my-date')` will not pop up the date picker for me. I'd like to find a way to test this from a user perspective, clicking on the input then clicking on a date in the calendar. Any ideas? Thanks!

**Comment by rodrigoyoshida** [comment]
It took me some time to figure it out how to test a component that uses ember-cli-bootstrap-datepicker. I believe there should be a "how to test" section on README because the fillIn test helper does not work. And even the @Maze-fr tip here does not work anymore, now the Ember tests no longer uses jQuery, so the datepicker method does not exist in that context. 

I had to import jQuery like this
`import $ from 'jquery';`

And then do it this way
`$(this.element).find('#myField').datepicker('setDate', new Date(2018, 8, 15));`

I would create a PR, but I am afraid this addon is abandoned, so I just hope anyone who has this problem can find the answer here.
