### ISSUE TITLE
Keyboard input is processed immediately, preventing other typing

### ISSUE THREAD

**Issue by dfalling** [soulim/ember-cli-bootstrap-datepicker#34]
When I try to enter a date in manually via text, today's date is filled in as soon as I type a single character.  For example typing "1" results in "05/03/2015" with the cursor at the end.  I have to click on different parts of the text date to change them.  I think this is caused by updateDatepicker() being called as soon as any change occurs.

**Comment by Hanastaroth** [comment]
See pull request #36 

This should do the work. But this is still no merged :cry:

**Comment by soulim** [comment]
The issue has been fixed in https://github.com/soulim/ember-cli-bootstrap-datepicker/pull/36. Huge thank you for your feedback!
