### ISSUE TITLE
Dynamic change of options

### ISSUE THREAD

**Issue by ewjoachim** [soulim/ember-cli-bootstrap-datepicker#38]
For now, I've been mostly happy with ember-cli-bootstrap-datepicker.

I just had a problem now, I need to change the startDate and endDate parameters after the creation of the object, so my start and end values are properties of my controller, but as far as I can tell, it does not change the datepicker 's min and max. I've been looking at the code, and if I undestrand correctly, these values are read only during the creation of the datepicker. How could I achieve such behavior ?

Thank you

**Comment by soulim** [comment]
Hey @ewjoachim! You problem has been fixed in https://github.com/soulim/ember-cli-bootstrap-datepicker/pull/37 that just got merged into master. I would be happy to get your feedback on this.

**Comment by soulim** [comment]
Just released `0.5.2`. It includes this feature :smile:

**Comment by ewjoachim** [comment]
Ha, I had started writing my own subclass and I ended up with the exact same code (well except that you have proper testing and I don't !) so I can say it's ok for me :)

Thanks a lot :)

**Comment by soulim** [comment]
Kudos to @aldhsu for his amazing work that made it possible :heart:

**Comment by soulim** [comment]
So I would consider this issue closed.
