### ISSUE TITLE
Warning on Ember 1.13.2

### ISSUE THREAD

**Issue by mjanda** [soulim/ember-cli-bootstrap-datepicker#39]
*WARNING: Binding style attributes may introduce cross-site scripting vulnerabilities; please ensure that values being bound are properly escaped. For more information, including how to disable this warning, see http://emberjs.com/deprecations/v1.x/#toc_binding-style-attributes.*

If I remove ```'style'``` from ```attributeBindings``` in ```addons/components/bootstrap-datepicker.js```, it goes away, but that's probably not the right solution.

// Of course I'm not setting any style myself.

**Comment by soulim** [comment]
Oh wow! Thank you very much @mjanda!

**Comment by OpakAlex** [comment]
@soulim some progress? maybe bind `_style` and make some property?

**Comment by adam-knights** [comment]
Looking at https://github.com/emberjs/ember.js/blob/master/packages/ember-views/lib/views/text_field.js and https://github.com/emberjs/ember.js/blob/master/packages/ember-views/lib/views/checkbox.js Ember itself no longer has style listed so I think it would be safe to remove it.
