### ISSUE TITLE
Embedded Calendar

### ISSUE THREAD

**Issue by ksnyde** [soulim/ember-cli-bootstrap-datepicker#4]
There are three basic display types:

![2014-12-27_01-15-30](https://cloud.githubusercontent.com/assets/980757/5560060/f75b702c-8d65-11e4-8651-c9dd87bec710.png)

The highlighted one on the right is referred to as an *embedded* or *inline* style: [docs](http://bootstrap-datepicker.readthedocs.org/en/release/markup.html#inline-or-embedded). Looking at your plugin I wasn't sure if it was able to support this.  Would love to use your addon but this style is critical for me.

**Comment by soulim** [comment]
Hey @ksnyde! I just added support for inline mode :wink: A new version of the npm package is not released yet, but everything is on master branch already.

You should use a separate `bootstrap-datepicker-inline` component to get an inline calendar, e.g.
```handlebars
{{bootstrap-datepicker-inline value=expiresAt}}
```

Also there's the demo page where you could play with all available options - http://sul.im/ember-cli-bootstrap-datepicker/

I'm going to release a new version of the npm package in one or two days. Just need to make sure everything works perfectly :smile:

**Comment by ksnyde** [comment]
:+1: Great! I'm off on something else for a few days but looking forward to getting that incorporated into my project when I'm back.

**Comment by soulim** [comment]
Version 0.3.0 has been released today. @ksnyde, please, let me know if you have issues with the inline mode. It works fine for me :wink:.

Happy coding! :rocket:

**Comment by ksnyde** [comment]
Will do. Should be able to check later today.
