### ISSUE TITLE
Computed property does not bind to input field

### ISSUE THREAD

**Issue by matixmatix** [soulim/ember-cli-bootstrap-datepicker#44]
The issue is that my date property does not bind to datepicker input when my component renders.

For demonstration purpose I added the display of actual bound property:

    {{filter.value}}
    {{bootstrap-datepicker value=filter.value autoclose=true class="form-control rt-input"}}

This template renders like this - input doesn't have the value displayed above, datepicker also doesn't have selected day marked:

![image](https://cloud.githubusercontent.com/assets/273660/8648410/bfd7578c-2960-11e5-9498-61fc5e5ec6fe.png)

**Comment by matixmatix** [comment]
solution: Date object

**Comment by et** [comment]
@soulim - can this be added to the docs? This is not obvious.
