### ISSUE TITLE
How to preset a Date?

### ISSUE THREAD

**Issue by juliankmazo** [soulim/ember-cli-bootstrap-datepicker#48]
Hi. I'm trying to preset the date that is shown in the component. But is not working

`{{bootstrap-datepicker startDate=startDateCheckIn' setDate=checkIn value=checkIn}}`

Sometime chekIn already have a date, so I want that the component render that date in the input.

**Comment by mkorfmann** [comment]
Hey,

What kind of property is checkIn in your case? Please double check if it's a date object, otherwise it won't work.

Cheerio
Manuel

**Comment by soulim** [comment]
Hey @juliankmazo! The `value` property should work for you in this case. @mkorfmann is totally correct, you need to make sure that you pass a native Javascript Data Object.

There's an example:

```handlebars
{{bootstrap-datepicker value=expiresAt}}
```

`expiresAt` holds a Data Object.

**Comment by juliankmazo** [comment]
Hi @soulim @mkorfmann 
Thanks for the response. You goys are totally right. I was creating the data object, but the date was created before the startDate, so of course that the component doesn't render that ;)

I fix my code now. Thank you guys so much.
