### ISSUE TITLE
Cleaning the text manually don't update the model

### ISSUE THREAD

**Issue by manuelsalvatori** [soulim/ember-cli-bootstrap-datepicker#50]
Hi, I'm having an issue with cleaning the selected date the datepicker.

If I set the value, from the code or selecting it from the UI, and than I delete the input content, the model doesn't get updated.
Using the clean embedded button it the event is correctly triggered and the model is updated.

Do I have to handle it manually?
Thanks

**Comment by soulim** [comment]
@manuelsalvatori do you use the component version from `master` branch or from npm repository?

This issue should be fixed in `master` branch. You could find more details in pull request https://github.com/soulim/ember-cli-bootstrap-datepicker/pull/35.

Let me know if code from `master` doesn't solve the issue for you.

**Comment by manuelsalvatori** [comment]
Hi thanks for the quick reply.
I have used "ember install ember-cli-bootstrap-datepicker" to install it.
In my bower file I have "bootstrap-datepicker": "~1.4.0".
In my package.json I have "ember-cli-bootstrap-datepicker": "0.5.3"
The console shows that it is installing via Bower:
git://github/eternicode/boostrap-datepicker.git#1.4.0

Is that right?
What to you suggest me to do to ovveride this?
Is it enough to put the direct github url in the bower file?

Thanks

**Comment by srisonti** [comment]
Just wanted to chime in here - I'm having the same issue with the model with the same versions that @manuelsalvatori has. 0.5.3 seems to be the `master` branch from the npm repository. Any idea how to fix this?

**Comment by soulim** [comment]
@manuelsalvatori, @srisonti [v0.5.4][1] has been released a couple of minutes ago. It should fix this issue. Please install it from the npm repository.

[1]: https://github.com/soulim/ember-cli-bootstrap-datepicker/releases/tag/v0.5.4

**Comment by manuelsalvatori** [comment]
Thank you
