### ISSUE TITLE
Ember 1.13.6 - unable to set start date or end date

### ISSUE THREAD

**Issue by dangreenisrael** [soulim/ember-cli-bootstrap-datepicker#51]
I'm getting an error of `Uncaught TypeError: Cannot read property 'datepicker' of undefined` for startDate and endDate.

A bit of digging shows that it is caused by `line 78` in `addon->components->datepicker-support.js`

`this.$()` is returning undefined.

Can someone else verify that this is a bug.

If it's not just me I'd be happy to work on a fix and make a pr

**Comment by mkorfmann** [comment]
Which version of ember-cli-bootstrap-datepicker are you using?

**Comment by dangreenisrael** [comment]
1.3.7  I just saw that is was fixed by [this commit] (https://github.com/soulim/ember-cli-bootstrap-datepicker/commit/62f46963d9221550476e2ef67cd44df28d0fa490)
