### ISSUE TITLE
JS Error: format.replace is not a function

### ISSUE THREAD

**Issue by HerveSeger** [soulim/ember-cli-bootstrap-datepicker#59]
Hi.

I use ember-cli-bootstrap-datepicker with ember-i18n for a bilingual app.

When I code in my template:
`
{{bootstrap-datepicker format=(t 'app.date.system') language=(t 'app.date.language') autoclose=true placeholder=(t 'app.date.display') class="form-control"}}
`
It fails here in bootstrap-datepicker.js:
``` js
parseFormat: function(format){
			// IE treats \0 as a string end in inputs (truncating the value),
			// so it's a bad format delimiter, anyway
			var separators = format.replace(this.validParts, '\0').split('\0'),
            ...
```
I get format.replace is not a function because the string returned by ember-i18n (the 't') is a SafeString object, not a pure String as parseFormat expects it.

A solution might be:
`format = format.toString()` 
because SafeString has a toString() method and it still works with a regular String.

**Comment by jelhan** [comment]
I could confirm the issue and the proposed solution to use `toString()`. @HerveSeger do you mind to make a pull request?

**Comment by HerveSeger** [comment]
sure, no problem.

**Comment by HerveSeger** [comment]
@jelhan 

I am pretty new on both Ember and Github so I want to make sure that I am on the right path.

The problem can be fixed in two ways:
 1. In my template the `format` attribute might reference a controller property that takes care of returning a string to `bootstrap datepicker`. No need for a pull request.
 2. We can add the following code that has been successfully tested:

    ```js
// [A]
// addon/components/datepicker-support.js
    setupBootstrapDatepicker: Ember.on('didInsertElement', function () {
		var self = this;

        //Fix issue #59
		var format = this.get('format');
		if (typeof format !== typeof Undefined && format !== typeof String) {
			if (typeof format.toString === typeof Function) {
				format = format.toString();
			} else {
				// No toString() function available - There is nothing else that can be done
				throw new Error("Invalid/unhandled object type for the format attribute.");
			}
		}

        this.$().
		datepicker({
			autoclose: this.get('autoclose'),
            calendarWeeks: this.get('calendarWeeks'),
			clearBtn: this.get('clearBtn'),
			container: this.get('widgetContainer'),
			daysOfWeekDisabled: this.get('daysOfWeekDisabled'),
			defaultViewDate: this.get('defaultViewDate'),
			disableTouchKeyboard: this.get('disableTouchKeyboard'),
			enableOnReadonly: this.get('enableOnReadonly'),
			endDate: this.get('endDate'),
			forceParse: this.get('forceParse'),
			format: format,
...
```

The code above is ready to ship but what bugs me is the following code:

```js
// [B]
// addon/components/datepicker-support.js
    	this.addObserver('format', function () {
			this.$().datepicker('format', this.get('format'));
			this.$().data('datepicker')._process_options({
				format: this.get('format')
			});
			this._updateDatepicker();
		});
```

Initially I had 
```js
// [C]
// addon/components/datepicker-support.js
...
    if (typeof format.toString === typeof Function) {
				this.set('format', format.toString());
			} else {
...
```
`this.set('format', format.toString())` in `[C]` was triggering `[B]`which is normal but strangely `this.get('format')` in `[B]` returns the previous object type/value (`SafeString`) and not the updated one (`String`) which I do not understand because it has been updated in `[A]`.
If I replace `[C]`by `[A]` then `[B]` is not called anymore. Ever. 
So for me the problem is fixed but at the same time I am not 100% satisfied by what I have done hence this looong explanation :)

Let me know if I missed something and if you agree with what I have coded then I can create the PR in no time since my branch `develop` has already been committed in my repo.

**Comment by jelhan** [comment]
Just had a short overview. I don't like the idea to change `format`. Wouldn't it be enough to call `toString()` on `this.get('format')` when it's passed to bootstrap datepicker? https://github.com/jelhan/ember-cli-bootstrap-datepicker/commit/306276fe42e3be6814565a362e5a8e3b60d55456

**Comment by HerveSeger** [comment]
@jelhan 
I agree with you and I just created a PR that implements a generic method to test/convert an attribute.

**Comment by jelhan** [comment]
Looks nice. Could you please fix the indent and create a PR? Perhaps a rebase to squash the commit into one would be nice. I don't know how @soulim feels about it.

**Comment by HerveSeger** [comment]
@jelhan 
Sorry for the confusion but I am learning git/Github/contributions the hard way here so I have closed my previous PR and restarted from scratch.
This time everything (including indentation) is ok.

**Comment by soulim** [comment]
Fixed in https://github.com/soulim/ember-cli-bootstrap-datepicker/pull/68. Thank you a lot!
