### ISSUE TITLE
How do I initialize the datepicker on route navigation?

### ISSUE THREAD

**Issue by NullVoxPopuli** [soulim/ember-cli-bootstrap-datepicker#69]
the date picker works if I refresh the page (or just manually type in the URL that has the datepicker)

but if I navigate to it, the datepicker isn't initialized, and the text field is just a text field.

**Comment by soulim** [comment]
Would be helpful if you could provide code, otherwise it's hard to understand what is going wrong.

**Comment by NullVoxPopuli** [comment]
Here are the two templates that I navigate between:

this one is at /events/:id//edit/
https://github.com/NullVoxPopuli/aeonvera-ui/blob/upgrade-to-ember-2/app/templates/events/show/edit/index.emblem

and

this one is at /events/:id/edit/options
https://github.com/NullVoxPopuli/aeonvera-ui/blob/upgrade-to-ember-2/app/templates/events/show/edit/options.emblem

If I type one of those paths in to the address bar, and then click a link-to that takes me to the other route, the second route's date-time-pickers don't work.

does that help?

**Comment by soulim** [comment]
Thank you! These links are helpful. Actually you are using different library, so this is a wrong repo for issue report :wink: 

You should ask at https://github.com/plusacht/ember-bootstrap-datetimepicker. Because you are using `bs-datetimepicker` component in templates, it should be `ember-bootstrap-datetimepicker` library.

**Comment by NullVoxPopuli** [comment]
oh. haha. sorry about that :-)

**Comment by soulim** [comment]
No problem :wink: Wish you a great day and hope you will find solution for the problem very soon!
