### ISSUE TITLE
Today button not working

### ISSUE THREAD

**Issue by ksnyde** [soulim/ember-cli-bootstrap-datepicker#7]
I have setup the calendar like so:

````hbs
{{bootstrap-datepicker-inline value=expiresAt autoclose=false todayBtn=true todayHighlight=true}}
````

With the `todayBtn=true` set I get the Today button but pressing it has no impact on the control. I've tried this on both the inline and non-inline versions of the control and they both appear to have this problem.

**Comment by soulim** [comment]
Will check that. It's definitely works on [the demo page](http://sul.im/ember-cli-bootstrap-datepicker/), when you navigate from the current month view and click on "Today" it returns you back to the current month.

**Comment by soulim** [comment]
Btw, I don't think you need to set `autoclose=true` for inline mode. Inline calendar can't be closed.

**Comment by soulim** [comment]
Just used your code on the demo page locally. It works (see screenshot).

![today-btn](https://cloud.githubusercontent.com/assets/2370/5620791/6c828914-952f-11e4-969c-d322ebb78f5e.gif)

Are you sure there's no other errors in the app?

**Comment by ksnyde** [comment]
Oh yeah the `autoclose` nonsense was me fiddling around. :)

**Comment by ksnyde** [comment]
I tried the use-case you demonstrated and it works fine for me too but try this:

- choose any date in the current month
- now press the "today" button ... nothing happens

It's possible this is defect in the control itself. If so they seem to be crushing defects at the moment so this should be brought quickly while they've still got their mojo.

**Comment by ksnyde** [comment]
Ya know I think a year or so ago I *did* an issue to the datetimepicker repo and if I'm not mistaken, they may have come back and said that was expected behaviour. I find it odd but I can create my own 'today' button at the bottom which works the way I would expect it ... I guess what I'm saying is maybe we should just close this.

> note: of course now the two-way binding issue I brought up has added importance for me

**Comment by soulim** [comment]
I'll close this issue because it's not related to the add-on. The bootstrap-datepicker is "responsible" for this behaviour of "Today" button.

Will fix the two-way binding ASAP.

**Comment by ksnyde** [comment]
:+1:

**Comment by NicholasJohn16** [comment]
I think there's another issue with the today button. It doesn't appear to be working on the demo page. If you click on the today button, it just refocuses on the input instead of select the current date.
