### ISSUE TITLE
Is this project abandoned? Publish new version.

### ISSUE THREAD

**Issue by cibernox** [soulim/ember-cli-bootstrap-datepicker#88]
I wanted some change that is in master but not in the last published version in NPM. Can someone publish a new version to the registry?

**Comment by soulim** [comment]
No worries @cibernox! I will publish a new version to NPM in a few hours. Thanks for using the component.

Btw, I'm pretty sure you could fetch the package directly from the master branch on GitHub.

**Comment by cibernox** [comment]
Oh yes, I can use it from master, but given that the change I wanted was in master I thought that asking was a good idea.

Thanks!

**Comment by soulim** [comment]
It took longer than expected, but you could get the latest version from NPM now.

Have a great day @cibernox! 😃

**Comment by cibernox** [comment]
Thanks!
